apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1 # Bir adet PostgreSQL pod'u çalıştırın
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        type: db
    spec:
      volumes:
      - name: postgresql-pvc
        persistentVolumeClaim:
          claimName: postgresql-pvc
      containers:
        - name: postgresql
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 250Mi
          image: postgres:14-alpine
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
               name: postgresql-config
               key: database
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
               name: postgresql-config
               key: user
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
               name: postgresql-config
               key: url
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
               name: postgresql-secret
               key: password
          - name: POSTGRES_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
               name: postgresql-secret
               key: root_password
          volumeMounts:
          - name: postgresql-pvc
            mountPath: /var/lib/postgresql/data
     
        



