
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=latest
        echo "Building and pushing image with tag $IMAGE_TAG"
        echo `pwd && ls`
        docker build -t aysegulakbaas1/java-web-app --target stage-1 .
        docker build -t aysegulakbaas1/java-web-app --target stage-2 .
        docker image tag aysegulakbaas1/java-web-app aysegulakbaas1/java-web-app:$IMAGE_TAG
        docker push aysegulakbaas1/java-web-app:$IMAGE_TAG

        kubectl apply -f postgresql.yaml
        kubectl apply -f postgresql-service.yaml
        kubectl apply -f postgresql-config.yaml
        kubectl apply -f postgresql-secret.yaml
